import React from 'react';
import { AlertCircle, Camera, Sparkles, ArrowRight } from 'lucide-react';

interface InstructionPageProps {
  onBegin: () => void;
}

export function InstructionPage({ onBegin }: InstructionPageProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-8 md:p-12 max-w-3xl w-full">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <AlertCircle className="w-10 h-10 text-indigo-600" />
          <h1 className="text-3xl text-gray-900">Before We Begin</h1>
        </div>

        {/* Important Notes - Merged */}
        <div className="space-y-6 mb-8">
          <div className="bg-indigo-50 border-l-4 border-indigo-500 rounded-r-lg p-6">
            <div className="space-y-4">
              {/* Real Photo */}
              <div className="flex items-start gap-3">
                <Camera className="w-6 h-6 text-indigo-600 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-base text-gray-900 mb-2">
                    <strong>1. What counts as a "Real Photo"?</strong>
                  </h3>
                  <p className="text-sm text-gray-700 leading-relaxed">
                    Real photos refer to photos taken by cameras. 
                    Post-processing such as color correction and tonal adjustments <strong>MAY</strong> be applied.
                    However, to reduce the difficulty, there are <strong>NO</strong> photos that post-processing with image synthesis technology, such as image stacks and focus stacking.
                  </p>
                </div>
              </div>

              {/* Divider */}
              <div className="border-t border-indigo-200"></div>

              {/* AI-Generated */}
              <div className="flex items-start gap-3">
                <Sparkles className="w-6 h-6 text-indigo-600 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-base text-gray-900 mb-2">
                    <strong>2. What counts as "AI-Generated Images?"</strong>
                  </h3>
                  <p className="text-sm text-gray-700 leading-relaxed">
                    AI-generated images refer to the pictures that were entirely generated by AI. 
                    To reduce the difficulty, there are <strong>NO</strong> photos that had undergone AI face swapping, AI blur removal, or AI addition 
                    or deletion of objects.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Call to Action */}
          <div className="bg-green-50 border-l-4 border-green-500 rounded-r-lg p-6">
            <p className="text-base text-gray-900 leading-relaxed">
              Now, try to identify the images in front of you as <strong>quickly</strong> and <strong>accurately</strong> as possible!
            </p>
          </div>
        </div>

        {/* Begin Button */}
        <button
          onClick={onBegin}
          className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white py-4 px-6 rounded-lg transition-all text-lg font-medium shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
        >
          Begin the Quiz!
          <ArrowRight className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
}