"use client";
import { Camera, Sparkles, ArrowRight } from "lucide-react";

interface InstructionPageProps {
  onBegin: () => void;
}

export function InstructionPage({ onBegin }: InstructionPageProps) {
  return (
    <div className="min-h-screen bg-[#F7E6C4]/30 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-8 md:p-12 max-w-3xl w-full">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <h1 className="text-3xl text-gray-900">
            Assumptions & Clarification
          </h1>
        </div>

        {/* Important Notes - Merged */}
        <div className="space-y-6 mb-8">
          <div className="bg-[#9E3B3B]/10 rounded-lg p-6">
            <div className="space-y-4">
              {/* Real Photo */}
              <div className="flex items-start gap-3">
                <Camera className="w-6 h-6 text-[#9E3B3B] flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-base text-gray-900 mb-2">
                    <strong>1. What we count as a "Real Photo"?</strong>
                  </h3>
                  <p className="text-sm text-gray-700 leading-relaxed">
                    Real photos refer to photos taken by cameras.
                    Post-processing such as color correction and tonal
                    adjustments <strong>MAY</strong> be applied. However, to
                    reduce the difficulty, there are <strong>NO</strong> photos
                    that have undergone post-processing with image synthesis
                    technology.
                  </p>
                </div>
              </div>

              {/* Divider */}
              <div className="border-t border-indigo-200"></div>

              {/* AI-Generated */}
              <div className="flex items-start gap-3">
                <Sparkles className="w-6 h-6 text-[#9E3B3B] flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-base text-gray-900 mb-2">
                    <strong>2. What we count as "AI-Generated Images?"</strong>
                  </h3>
                  <p className="text-sm text-gray-700 leading-relaxed">
                    AI-generated images refer to the pictures that were entirely
                    generated by AI. To reduce the difficulty, there are{" "}
                    <strong>NO</strong> photos that have undergone AI face
                    swapping, AI blur removal, or AI addition or deletion of
                    objects.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Call to Action */}
          <div className="bg-[#606C5D]/30 border-l-4 border-[#606C5D] rounded-r-lg p-6">
            <p className="text-base text-gray-900 leading-relaxed">
              Now, try to identify the images in front of you as{" "}
              <strong>quickly</strong> and <strong>accurately</strong> as
              possible!
            </p>
          </div>
        </div>

        {/* Begin Button */}
        <button
          onClick={onBegin}
          className="w-full bg-[#606C5D] hover:bg-[#606C5D]/50 text-white py-4 px-6 rounded-lg transition-all text-lg font-medium shadow-lg hover:shadow-xl flex items-center justify-center gap-2"
        >
          Begin the Quiz!
          <ArrowRight className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
}
