// Image dataset with labels indicating whether each image is AI-generated
export interface ImageData {
  id: string;
  url: string;
  isAIGenerated: boolean;
  source?: string; // Optional field for image source or photographer
}

export const imageDataset: ImageData[] = [
  {
    id: "img001", // 风景 真 by Taylor pendleton https://www.taylorpendleton.com/natgeo
    url: "/images/real5.jpg",
    isAIGenerated: false,
    source: "Taylor pendleton"
  },
  {
    id: "img002", 
    url: "https://images.unsplash.com/photo-1616386573884-22531fd226e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYW5kc2NhcGUlMjBuYXR1cmUlMjBtb3VudGFpbnxlbnwxfHx8fDE3NzAzODQ4ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  },
  {
    id: "img003",
    url: "https://images.unsplash.com/photo-1695067438561-75492f7b6a9c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcmNoaXRlY3R1cmUlMjBidWlsZGluZ3xlbnwxfHx8fDE3NzAzMjA1ODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: false
  },
  {
    id: "img004",
    url: "https://images.unsplash.com/photo-1705254613735-1abb457f8a60?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGFydCUyMGNvbG9yZnVsfGVufDF8fHx8MTc3MDQwNTc2Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  },
  {
    id: "img005",
    url: "https://images.unsplash.com/photo-1513563326940-e76e4641069e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaXR5JTIwc2t5bGluZSUyMG5pZ2h0fGVufDF8fHx8MTc3MDM4MDE4Mnww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: false
  },
  {
    id: "img006",
    url: "https://images.unsplash.com/photo-1698309627162-8ce7442ab855?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmb29kJTIwcGhvdG9ncmFwaHklMjBtZWFsfGVufDF8fHx8MTc3MDM3OTAwNXww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  },
  {
    id: "img007", // 群像 真 by Rod Waddington
    url: "/images/real2.jpg",
    isAIGenerated: false,
    source: "Rod Waddington"
  },
  {
    id: "img008", // 食物 真 by John Cullen https://www.johncullenphotographer.com/fooddrink 
    url: "/images/real3.jpg",
    isAIGenerated: false,
    source: "John Cullen"
  },
  {
    id: "img009", // 小动物 真 by Rod Waddington 
    url: "/images/real1.jpg",
    isAIGenerated: false,
    source: "Rod Waddington"
  },
  {
    id: "img010", // 街道 真 by Fred Herzog
    url: "/images/real4.jpg",
    isAIGenerated: false,
    source: "Fred Herzog"
  },
  {
    id: "img011", //人像，假 https://leonfurze.com/2024/08/23/ai-images-are-already-more-realistic-than-you-think/
    url: "/images/fake1.jpg",
    isAIGenerated: true,
    source: "Leon Furze"
  },
  {
    id: "img012", // 人像 假 generated by Nano Banana pro 
    url: "/images/fake2.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img013", // 书桌 假 generated by Nano Banana pro 
    url: "/images/fake3.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img014", // 风景 假 generated by Kling O3 
    url: "/images/fake4.jpg",
    isAIGenerated: true,
    source: "Kling O3"
  },
  {
    id: "img015", //城市景观 假 generated by Nano Banana pro
    url: "/images/fake5.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img016",
    url: "https://images.unsplash.com/photo-1661362758906-3a85700516c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHxzdW5zZXQlMjBza3klMjBjbG91ZHN8ZW58MXx8fHwxNzcwMzY3OTQ3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  },
  {
    id: "img017",
    url: "https://images.unsplash.com/photo-1606388701602-2e3727da5b28?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHx3aW50ZXIlMjBzbm93JTIwbGFuZHNjYXBlfGVufDF8fHx8MTc3MDMyMTAzMnww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: false
  },
  {
    id: "img018",
    url: "https://images.unsplash.com/photo-1642316655095-6349aa377ce5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHx0ZWNobm9sb2d5JTIwY29tcHV0ZXIlMjBkaWdpdGFsfGVufDF8fHx8MTc3MDQwNTc2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  },
  {
    id: "img019",
    url: "https://images.unsplash.com/photo-1696245843980-79b69e076ffa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtdXNpYyUyMGluc3RydW1lbnRzJTIwZ3VpdGFyfGVufDF8fHx8MTc3MDQwNTc2N3ww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: false
  },
  {
    id: "img020",
    url: "https://images.unsplash.com/photo-1704048001164-9e454dd611e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYXJkZW4lMjBwbGFudHMlMjBmbG93ZXJzfGVufDF8fHx8MTc3MDMwOTUwNnww&ixlib=rb-4.1.0&q=80&w=1080",
    isAIGenerated: true
  }
];

// Function to get a random selection of images
export function getRandomImages(count: number): ImageData[] {
  const shuffled = [...imageDataset].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Function to get fixed 10 images per section, but shuffled for each player
export function getFixedShuffledImages(): ImageData[] {
  const firstSection = [...imageDataset.slice(0, 10)].sort(() => Math.random() - 0.5);
  const secondSection = [...imageDataset.slice(10, 20)].sort(() => Math.random() - 0.5);
  return [...firstSection, ...secondSection];
}
