// Image dataset with labels indicating whether each image is AI-generated
export interface ImageData {
  id: string;
  url: string;
  isAIGenerated: boolean;
  source?: string; // Optional field for image source or photographer
}

export const imageDataset: ImageData[] = [
  {
    id: "img001", // 风景 真 by Taylor pendleton https://www.taylorpendleton.com/natgeo
    url: "./images/real5.jpg",
    isAIGenerated: false,
    source: "Taylor Pendleton"
  },
  {
    id: "img002",
    url: "./images/fake6.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img003",
    url: "./images/fake7.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img004",
    url: "./images/fake8.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img005",
    url: "./images/fake9.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img006",
    url: "./images/fake10.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img007", // 群像 真 by Rod Waddington
    url: "./images/real2.jpg",
    isAIGenerated: false,
    source: "Rod Waddington"
  },
  {
    id: "img008", // 食物 真 by John Cullen https://www.johncullenphotographer.com/fooddrink 
    url: "./images/real3.jpg",
    isAIGenerated: false,
    source: "John Cullen"
  },
  {
    id: "img009", // 小动物 真 by Rod Waddington 
    url: "./images/real1.jpg",
    isAIGenerated: false,
    source: "Rod Waddington"
  },
  {
    id: "img010", // 街道 真 by Fred Herzog
    url: "./images/real4.jpg",
    isAIGenerated: false,
    source: "Fred Herzog"
  },
  {
    id: "img011", //人像，假 https://leonfurze.com/2024/08/23/ai-images-are-already-more-realistic-than-you-think/
    url: "./images/fake1.jpg",
    isAIGenerated: true,
    source: "Leon Furze"
  },
  {
    id: "img012", // 人像 假 generated by Nano Banana pro 
    url: "./images/fake2.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img013", // 书桌 假 generated by Nano Banana pro 
    url: "./images/fake3.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img014", // 风景 假 generated by Kling O3 
    url: "./images/fake4.jpg",
    isAIGenerated: true,
    source: "Kling O3"
  },
  {
    id: "img015", //城市景观 假 generated by Nano Banana pro
    url: "./images/fake5.jpg",
    isAIGenerated: true,
    source: "Nano Banana pro"
  },
  {
    id: "img016",
    url: "./images/real6.jpg",
    isAIGenerated: false,
    source: "Farnaz Kohankhaki from pexels.com"
  },
  {
    id: "img017",
    url: "./images/real7.jpg",
    isAIGenerated: false,
    source: "Nataliya Vaitkevich from pexels.com"
  },
  {
    id: "img018",
    url: "./images/real8.jpg",
    isAIGenerated: false,
    source: "Ryan Lansdown from pexels.com"
  },
  {
    id: "img019",
    url: "./images/real9.jpg",
    isAIGenerated: false,
    source: "Haoyu Liu"
  },
  {
    id: "img020",
    url: "./images/real10.jpg",
    isAIGenerated: false,
    source: "Haoyu Liu"
  }
];

// Function to get a random selection of images
export function getRandomImages(count: number): ImageData[] {
  const shuffled = [...imageDataset].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Function to get fixed 10 images per section, but shuffled for each player
export function getFixedShuffledImages(): ImageData[] {
  const firstSection = [...imageDataset.slice(0, 10)].sort(() => Math.random() - 0.5);
  const secondSection = [...imageDataset.slice(10, 20)].sort(() => Math.random() - 0.5);
  return [...firstSection, ...secondSection];
}
